pronat/home/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views


app_name = 'prona'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^prona_dataset$', views.prona_dataset, name='prona_dataset'),
    url(r'^(?P<biznes_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^search-results/$', views.prona_query, name='search-results'),
    url(r'^prona/(?P<user>[0-9]+)/$', views.pronat_mia, name='pronat_mia'),
    url(r'^(?P<pk>[0-9]+)/detail/$', views.prona_detail, name='prona_detail'),
    url(r'^prona/add/$', login_required(views.PronaCreate.as_view()), name='prona-add'),
    url(r'^prona/(?P<pk>[0-9]+)/update/$', login_required(views.PronaUpdate.as_view()), name='prona-update'),
    url(r'^prona/(?P<pk>[0-9]+)/delete/$', login_required(views.PronaDelete.as_view()), name='prona-delete'),
    url(r'^login/$', views.LoginView, name='login'),
    url(r'^logout/$', views.LogoutView, name='logout'),
    url(r'^register/$', views.RegisterView, name='register'),
]

pronat/pronat/urls.py
from django.conf.urls import include,url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls')),

]

pronat/home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.contrib.gis.db import models


# Create your models here.
class lloji (models.Model):
    lloji = models.CharField(max_length=250)

    def __str__(self):
        return self.lloji

class biznes (models.Model):
    biznes = models.CharField(max_length=250)

    def __str__(self):
        return self.biznes

class status (models.Model):
    status = models.CharField(max_length=250)

    def __str__(self):
        return self.status

class qytet (models.Model):
    qytet = models.CharField(max_length=250)

    def __str__(self):
        return self.qytet

class rruget (models.Model):
    emri = models.CharField(max_length=250)

    def __unicode__(self):
        return self.emri

class zona (models.Model):
    zona = models.CharField(max_length=250)
    id_qytet = models.ForeignKey(qytet, on_delete=models.CASCADE)

    def __unicode__(self):
        return u"%s" % self.zona

class vendodhje (models.Model):
    id_rruga = models.ForeignKey(rruget, on_delete=models.CASCADE)
    id_zona = models.ForeignKey(zona, on_delete=models.CASCADE)

    def __unicode__(self):
        return u'%s - %s' % (self.id_rruga, self.id_zona)




class prona (models.Model):
    id_vendodhje = models.ForeignKey(vendodhje, default='',on_delete=models.CASCADE)
    id_lloji = models.ForeignKey(lloji, default='',on_delete=models.CASCADE)
    cmimi = models.IntegerField()
    dhoma = models.IntegerField()
    banjo = models.IntegerField()
    size = models.IntegerField()
    titulli = models.CharField(max_length=250)
    pershkrim = models.CharField(max_length=1000)
    id_biznes = models.ForeignKey(biznes, default='',on_delete=models.CASCADE)
    status = models.IntegerField()
    geom = models.PointField()
    url = models.CharField(max_length=100)
    hits = models.IntegerField()
    id_user = models.ForeignKey(User, on_delete=models.CASCADE)
    creation_date = models.DateField(default=datetime.datetime.now)
    modif_date = models.DateField(default=datetime.datetime.now)
    sponsorizuar = models.IntegerField()
    objects = models.GeoManager()

    def get_absolute_url(self):
        return reverse('prona:prona_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.titulli


class atributi (models.Model):
    id_prona = models.ForeignKey(prona, on_delete=models.CASCADE)
    atributi = models.CharField(max_length=250)
    vlera = models.CharField(max_length=250)

class foto (models.Model):
    url = models.CharField(max_length=200)
    id_prona = models.ForeignKey(prona, on_delete=models.CASCADE)
    kryesore = models.IntegerField()

pronat/home/forms.py
from django.contrib.auth import (authenticate, get_user_model, login, logout)
from django.contrib.auth.admin import User
from django import forms
from .models import prona




User = get_user_model()

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        if username and password:
            user = authenticate(username=username, password=password)
            if username and password:
                if not user:
                    raise forms.ValidationError("This user does not exist")
                if not user.check_password(password):
                    raise forms.ValidationError("Incorrect password")
                if not user.is_active:
                    raise forms.ValidationError("This user is not longer active")
            return super(UserLoginForm, self).clean(*args, **kwargs)

class UserRegistrationForm(forms.ModelForm):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    email = forms.EmailField(label='Email Address')
    email2 = forms.EmailField(label='Confirm Email')
    class Meta:
        model = User
        fields = ['username', 'email', 'email2', 'password']

    def clean(self, *args, **kwargs):
        print (self.cleaned_data)
        email = self.cleaned_data.get('email')
        email2 = self.cleaned_data.get('email2')
        print (email, email2)
        if email != email2:
            raise forms.ValidationError("Emails must match")
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("This email has already been register")

            return super(UserRegistrationForm, self).clean(*args, **kwargs)

pronat/home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate,  login, logout
from models import *
from forms import UserLoginForm, UserRegistrationForm
from django.core.serializers import serialize
from django.http import HttpResponse
from django import forms
from leaflet.forms.fields import PointField
from leaflet.forms.widgets import LeafletWidget
from django.db.models import Q


# Create your views here.
def home (request):
    a = biznes.objects.all()
    return render(request,'prona/home.html',{'a': a})

def prona_dataset(request):
    pronat = serialize('geojson', prona.objects.all())
    return HttpResponse(pronat, content_type='json')
def detail (request, biznes_id):
    a = biznes.objects.all()
    b = prona.objects.all()
    d = b.filter(id_biznes_id = biznes_id)
    return render(request,'prona/prona.html',{'d': d, 'a':a})

def prona_query (request):
    if request.method == 'GET':
        queryset_list = prona.objects.all()
        query = request.GET.get("search", None)
        if query:
            queryset_list = queryset_list.filter(
                Q(id_vendodhje__id_rruga__emri__icontains=query)|
                Q(id_vendodhje__id_zona__zona__icontains=query)
            )

        return render(request,'prona/search-results.html',{'queryset_list': queryset_list}, content_type='json')
def prona_detail(request, pk):
    c = get_object_or_404(prona, pk=pk)
    e = prona.objects.filter(pk = pk)
    f = c.hits
    g = f+1
    h = e.update(hits = g)
    return render(request, 'prona/prona_detail.html', {'c': c, 'h': h })

class YourMapWidget(LeafletWidget):
    geometry_field_class = 'geom'
class PronaAdd(forms.ModelForm):
    geom = PointField()
    class Meta:
        model = prona
        fields = ['id_vendodhje', 'id_lloji', 'cmimi', 'dhoma', 'banjo', 'size', 'titulli', 'pershkrim', 'id_biznes', 'status', 'url', 'hits', 'creation_date', 'modif_date', 'sponsorizuar', 'geom', 'id_user',]
        widgets = {'geom': YourMapWidget()}


class PronaCreate(CreateView):
    model = prona
    form_class = PronaAdd
    template_name = 'prona/prona_form.html'


    def save_model(self, request, obj, ):
        if not obj.User.id:
            obj.User = request.user
        obj.save()


class PronaUpdate(UpdateView):
    model = prona
    fields = ['id_vendodhje', 'id_lloji', 'cmimi', 'dhoma', 'banjo', 'size', 'titulli', 'pershkrim', 'id_biznes', 'status', 'url', 'hits', 'creation_date', 'modif_date', 'sponsorizuar', 'geom']
    template_name = 'prona/prona_form.html'


class PronaDelete(DeleteView):
    model = prona
    success_url = reverse_lazy('prona:home')

def LoginView(request):
    print (request.user.is_authenticated())
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        login(request, user)
        print (request.user.is_authenticated())
        return redirect("/home/")

    return render(request, "prona/login_form.html", {"form": form})

def RegisterView(request):
    print (request.user.is_authenticated())
    forms = UserRegistrationForm(request.POST or None)
    if forms.is_valid():
        user = forms.save(commit=False)
        password = forms.cleaned_data.get('password')
        user.set_password(password)
        user.save()

        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)
        return redirect("/home/")

    return render(request, "prona/registration_form.html", {"forms": forms})

def LogoutView(request):
    logout(request)
    print (request.user.is_authenticated())
    return redirect("/home/")
    return render(request, 'prona/home.html', {})

def pronat_mia (request, user):
    e = prona.objects.all()
    f = e.filter(id_user_id = user)
    return render(request,'prona/pronat_mia.html', {'f': f})

pronat/home/templates/prona/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}pronat.al{% endblock %}</title>
    {% load staticfiles %}
    {% load static %}
    {% load leaflet_tags %}
    {% leaflet_js %}
    {% leaflet_css %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'prona/style.css' %}"/>
    <script type="text/javascript" src="{% static 'dist/leaflet.ajax.js' %}"></script>
    <script type="text/javascript" src="{% static 'dist/ajax.js' %}"></script>
    <script type="text/javascript" src="{% static 'dist/leaflet-search.js' %}"></script>
    <link rel="stylesheet" href="{% static 'leaflet/dist/leaflet.awesome-markers.css' %} ">
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.css" />
    <script src="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse" >
    <div class="container-fluid">
        <!-- header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'prona:home' %}"><span class="text-white"> Pronat.AL</span></a>
        </div>
        <!-- butonat e tjere -->
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'prona:home' %}">
                        <span class="text-white glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; <span class="text-white">Rreth PRONAT.AL</span>
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'prona:detail' 1%}">
                        <span class="text-white glyphicon glyphicon-barcode" aria-hidden="true"></span>&nbsp; <span class="text-white">PRONA ME QERA</span>
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'prona:detail' 2%}">
                        <span class="text-white glyphicon glyphicon-qrcode" aria-hidden="true"></span>&nbsp; <span class="text-white">PRONA NE SHITJE</span>
                    </a>
                </li>

                <li class="">
                    <a href="#">
                        <span class="text-white glyphicon glyphicon-earphone" aria-hidden="true"></span>&nbsp; <span class="text-white">KONTAKT</span>
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">

                {% if user.is_authenticated %}
                    <li class="">
                        <a href="{% url 'prona:pronat_mia' user.id %}">
                            <span class="text-white glyphicon glyphicon-plus " aria-hidden="true"></span>&nbsp; <span class="text-white">PRONAT E MIA</span>
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'prona:prona-add' %}">
                            <span class="text-white glyphicon glyphicon-plus " aria-hidden="true"></span>&nbsp; <span class="text-white">SHTO PRONE</span>
                        </a>
                    </li>

                    <li class="">
                        <a href="{% url 'prona:logout' %}"><span class="text-white">Welcome, {{ user.username }}.</span>
                            <span class="text-white glyphicon glyphicon-log-out " aria-hidden="true"></span>&nbsp; <span class="text-white">Dil</span>
                        </a>
                    </li>
                {% else %}
                    <li class="">
                        <a href="{% url 'prona:login' %}" method="POST">{% csrf_token %}
                            <span class="glyphicon glyphicon-log-in text-white" aria-hidden="true"></span>&nbsp; <span class="text-white">HYR</span>
                         </a>
                    </li>
                    <li class="">
                        <a href="{% url 'prona:register' %}" method="get" >{% csrf_token %}
                            <span class="glyphicon glyphicon-user text-white" aria-hidden="true"></span>&nbsp; <span class="text-white">REGJISTROHU</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

pronat/home/templates/prona/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>

    </div>
{% endfor %}

pronat/home/templates/prona/home.html
{% extends 'prona/base.html' %}
{% block body %}
<link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript">
</script> <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>

    {% if a %}
    {% include 'prona/lealfet_home.html' %}
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            <div class="property-form-box">
                <h2 class="heading text-center">GJEJ <span class="accent">PRONËN </span>QË PO <span class="accent">KËRKON</span> </h2>
                <form id="property-main-form" method="get" action="search-results" class="property-main-form">
                    <div class="controls">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="btn-group btn-group-justified">
                                    {% for biznes in a %}
                                    <a href="{% url 'prona:detail' biznes.id %}">
                                        <label class="btn btn-primary col-sm-12">{{ biznes.biznes }}</label>
                                    </a>

                                    {% endfor %}

                                </div>
                                <form class="navbar-form navbar-left" role="search" method="GET" action="{% url 'prona:search-results'  %}">
                                    <div class="form-group" >
                                        <input type="text" class="form-control" id = "search" name="search" placeholder="Kerko rruge ose lagje">
                                    </div>
                                    <button type="submit"  class="btn btn-deafult glyphicon glyphicon-search" id = "submit"></button>
                                </form>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% else %}
        <h3> You don't have any albums</h3>
    {% endif %}
{% endblock %}

pronat/home/templates/prona/lealfet_home.html
{% load staticfiles %}
{% load static %}
{% load leaflet_tags %}
{% leaflet_js %}
{% leaflet_css %}
<script type="text/javascript" src="{% static 'dist/leaflet.ajax.js' %}"></script>
<script type="text/javascript">

    var geojsonMarkerOptions = {
        radius: 8,
        fillColor: "#ff7800",
        color: "#000",
        weight: 1,
        opacity: 1,
        fillOpacity: 0.8
    };
    var geojsonMarkerOptions1 = {
        radius: 8,
        fillColor: "#fff",
        color: "#000",
        weight: 1,
        opacity: 1,
        fillOpacity: 0.8
    };
    function out_layer(map, options){

        var dataset = new L.GeoJSON.AJAX(" {% url 'prona:prona_dataset' %}",{
            onEachFeature: onEachFeature,
            pointToLayer: function (feature, latlng) {
                if (feature.properties.id_biznes === 1){
                    return L.circleMarker(latlng, geojsonMarkerOptions);
                }else{
                    return L.circleMarker(latlng, geojsonMarkerOptions1);
                }
            }
        });
        dataset.addTo(map);
    }


    function onEachFeature(feature, layer) {
        if (feature.properties.id_biznes === 1){

            layer.bindPopup("<b>Cmimi:</b> " + feature.properties.cmimi+
                "<br><b>Dhoma: </b>" + feature.properties.dhoma+
                "<br><b>Banjo: </b>" + feature.properties.banjo+
                "<br><b>Prona jepet me qera </b>"+
                "<br>" + "<b><a href=http://127.0.0.1:8000/home/" +feature.properties.pk + "/detail/>Shiko Pronën</a></b>");

        } else {
            layer.bindPopup("<b>Cmimi:</b> " + feature.properties.cmimi+
                "<br><b>Dhoma: </b>" + feature.properties.dhoma+
                "<br><b>Banjo: </b>" + feature.properties.banjo+
                "<br><b>Prona është në shitje</b>"+
                "<br>" + "<b><a href=http://127.0.0.1:8000/home/" +feature.properties.pk + "/detail/>Shiko Pronën</a></b>");
        }
    }

</script>
{% leaflet_map "map" callback="window.out_layer" %}

pronat/home/templates/prona/prona_detail.html
{% extends 'prona/base.html' %}
{% block body %}
    {% if c %}
    {% include 'prona/leaflet_filter.html' %}
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <div class="property-detail-box">
                <h2 class="heading text-center">GJEJ <span class="accent">PRONËN </span>QË PO <span class="accent">KËRKON</span> </h2>
                    <div class="controls">
                        <ul class="">
                            <h1> {{ c.titulli }}</h1>
                            <h3> {{ c.cmimi }}</h3>
                            <h4> {{ c.id_vendodhje}}</h4>
                            <h4> {{ c.id_lloji }}</h4>
                            <h4> {{ c.dhoma }}</h4>
                            <h4> {{ c.banjo }}</h4>
                            <h4> {{ c.size }}</h4>
                            <h4> {{ c.pershkrim }}</h4>
                            <h4> {{ c.id_biznes }}</h4>
                            <h4> {{ c.hits }}</h4>
                            <h4> {{ c.id_user }}</h4>
                            <script type="text/javascript">
                                function out_layer(map, options){
                                    var dataset = new L.GeoJSON.AJAX(" {% url 'prona:prona_dataset' %}",{
                                        filter: us,
                                        pointToLayer: function(feature, latlng){
                                            return L.marker(latlng, {});


                                        },
                                        onEachFeature: onEachFeature,

                                    });


                                    function onEachFeature(feature, layer) {
                                            layer.bindPopup("<b>Cmimi:</b> " + feature.properties.cmimi+
                                                "<br><b>Dhoma: </b>" + feature.properties.dhoma+
                                                "<br><b>Titulli: </b>" + feature.properties.titulli+
                                                "<br><b>Banjo: </b>" + feature.properties.banjo);
                                     }
                                    dataset.on('click', function(e){
                                        map.setView(e.latlng, 18);
                                    });
                                    map.on("load",function() { console.log("all visible tiles have been loaded") });
                                    dataset.addTo(map);
                                    function us(feature) {
                                        if (feature.properties.pk === "{{ c.id }}") return true
                                    }
                                }
                            </script>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

pronat/home/templates/prona/pronat_mia.html
{% extends 'prona/base.html' %}

{% block body %}

    {% if f %}
    {% include 'prona/leaflet_filter.html' %}
        <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            <div class="property-detail-box">
                <h2 class="heading text-center">GJEJ <span class="accent">PRONËN </span>QË PO <span class="accent">KËRKON</span> </h2>
                <div class="controls">

                    <ul class="ul_prona_detail">
                        {% for prona in f %}
                        <li class="li_prona_detail">
                            <h3> {{ prona.id_lloji }}</h3>
                            <h5> Çmimi: {{ prona.cmimi }}</h5>
                            <h5> Sipërfaqa: {{prona.size}}</h5>
                            <h6> {{ prona.id_vendodhje }}</h6>

                            {% if user.is_authenticated %}

                                <form action="{% url 'prona:prona_detail' prona.id %}" method="get" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="prona_id" value="{{ prona.id}}"/>
                                    <button type="submit" class="btn btn-default btn-sm text-white">
                                        <span class="glyphicon glyphicon-eye-open"></span>&nbsp; Shiko
                                    </button>
                                </form>
                                 <form action="{% url 'prona:prona-update' prona.id %}" method="get" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="prona_id" value="{{ prona.id}}"/>
                                    <button type="submit" class="btn btn-default btn-sm text-white">
                                        <span class="glyphicon glyphicon-edit"></span>&nbsp; Edit
                                    </button>
                                </form>

                                <form action="{% url 'prona:prona-delete' prona.id%}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="prona_id" value="{{ prona.id}}"/>
                                    <button type="submit" class="btn btn-default btn-sm text-white">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>
                                <script type="text/javascript">
                                    function out_layer(map, options){
                                        var dataset = new L.GeoJSON.AJAX(" {% url 'prona:prona_dataset' %}",{filter: us, onEachFeature: onEachFeature});
                                        dataset.addTo(map);
                                        function us(feature) {
                                            if (feature.properties.id_user === {{ prona.id_user_id }}) return true
                                        }
                                    }
                                    function onEachFeature(feature, layer) {
                                        layer.bindPopup("<b>Cmimi:</b> " + feature.properties.cmimi+
                                                "<br><b>Dhoma: </b>" + feature.properties.dhoma+
                                                "<br><b>Banjo: </b>" + feature.properties.banjo+
                                                "<br>" + "<b><a href=http://127.0.0.1:8000/home/" +feature.properties.pk + "/detail/>Shiko Pronën</a></b>");
                                    }

                                </script>

                            {% else %}
                                <form action="{% url 'prona:prona_detail' prona.id %}" method="get" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="prona_id" value="{{ prona.id}}"/>
                                    <button type="submit" class="btn btn-default btn-sm text-white">
                                        <span class="glyphicon glyphicon-eye-open"></span>&nbsp; Shiko
                                    </button>
                                </form>
                            {% endif %}
                        </li>
                        {% endfor %}
                    </ul>

                </div>
            </div>
        </div>
        </div>
    {% else %}
        <h3> You don't have any prona</h3>
    {% endif %}
{% endblock %}

pronat/home/templates/prona/search-results.html
{% extends 'prona/base.html' %}

{% block body %}

    {% if queryset_list %}
    {% include 'prona/leaflet_filter.html' %}
        <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            <div class="property-detail-box">
                <h2 class="heading text-center">GJEJ <span class="accent">PRONËN </span>QË PO <span class="accent">KËRKON</span> </h2>
                <div class="controls">

                    <ul class="ul_prona_detail">
                        {% for prona in queryset_list %}
                            <script type="text/javascript">
                            var geojsonMarkerOptions = {
                                    radius: 8,
                                    fillColor: "#ff7800",
                                    color: "#000",
                                    weight: 1,
                                    opacity: 1,
                                    fillOpacity: 0.8
                                };
                                var geojsonMarkerOptions1 = {
                                    radius: 8,
                                    fillColor: "#fff",
                                    color: "#000",
                                    weight: 1,
                                    opacity: 1,
                                    fillOpacity: 0.8
                                };



                                function out_layer(map, options){
                                    var dataset = new L.GeoJSON.AJAX(" {% url 'prona:prona_dataset' %}",{
                                        pointToLayer: pointToLayer,

                                        onEachFeature: onEachFeature});

                                    dataset.addTo(map);

                                }
                                function pointToLayer(feature, latlng){
                                    if (feature.properties.id_biznes === 1){
                                        return L.circleMarker(latlng, geojsonMarkerOptions);
                                    }else{
                                        return L.circleMarker(latlng, geojsonMarkerOptions1);
                                    }
                                }
             

                                function us(feature) {
                                        if (feature.properties.id_vendodhje === {{prona.id_vendodhje_id}}) return true
                                    }
                                 console.log(us);
                                function onEachFeature(feature, layer) {

                                    layer.bindPopup("<b>Cmimi:</b> " + feature.properties.cmimi+
                                            "<br><b>Dhoma: </b>" + feature.properties.dhoma+
                                            "<br><b>Banjo: </b>" + feature.properties.banjo+
                                            "<br>" + "<b><a href=http://127.0.0.1:8000/home/" +feature.properties.pk + "/detail/>Shiko Pronën</a></b>");
                                }

                            </script>
                        <li class="li_prona_detail">
                            <h3> {{ prona.id_lloji }}</h3>
                            <h5> Çmimi: {{ prona.cmimi }}</h5>
                            <h5> Sipërfaqa: {{prona.size}}</h5>
                            <h6> {{ prona.id_vendodhje }}</h6>
                            <h6> {{ prona.id_vendodhje_id }}</h6>
                            <form action="{% url 'prona:prona_detail' prona.id %}" method="get" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="prona_id" value="{{ prona.id}}"/>
                                <button type="submit" class="btn btn-default btn-sm text-white">
                                    <span class="glyphicon glyphicon-eye-open"></span>&nbsp; Shiko
                                </button>
                            </form>

                        </li>
                        {% endfor %}
                    </ul>

                </div>
            </div>
        </div>
        </div>
    {% else %}
        <h3> You don't have any prona</h3>
    {% endif %}
{% endblock %}